# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 480)
        MainWindow.setMinimumSize(QtCore.QSize(660, 480))
        MainWindow.setMaximumSize(QtCore.QSize(660, 480))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_OpenLog = QtWidgets.QPushButton(self.centralwidget)
        self.btn_OpenLog.setGeometry(QtCore.QRect(470, 380, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.btn_OpenLog.setFont(font)
        self.btn_OpenLog.setObjectName("btn_OpenLog")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_ReadAppVer = QtWidgets.QPushButton(self.groupBox)
        self.btn_ReadAppVer.setGeometry(QtCore.QRect(140, 20, 161, 21))
        self.btn_ReadAppVer.setObjectName("btn_ReadAppVer")
        self.lineEdit_AppVersion = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_AppVersion.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.lineEdit_AppVersion.setReadOnly(True)
        self.lineEdit_AppVersion.setObjectName("lineEdit_AppVersion")
        self.btn_ReadBootVer = QtWidgets.QPushButton(self.groupBox)
        self.btn_ReadBootVer.setGeometry(QtCore.QRect(470, 20, 161, 21))
        self.btn_ReadBootVer.setObjectName("btn_ReadBootVer")
        self.lineEdit_BootVersion = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_BootVersion.setGeometry(QtCore.QRect(340, 20, 121, 20))
        self.lineEdit_BootVersion.setReadOnly(True)
        self.lineEdit_BootVersion.setObjectName("lineEdit_BootVersion")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 641, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_GotoBoot = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_GotoBoot.setGeometry(QtCore.QRect(300, 20, 331, 21))
        self.btn_GotoBoot.setObjectName("btn_GotoBoot")
        self.lineEdit_AccessCode = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_AccessCode.setGeometry(QtCore.QRect(10, 20, 281, 20))
        self.lineEdit_AccessCode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_AccessCode.setMaxLength(4)
        self.lineEdit_AccessCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_AccessCode.setReadOnly(False)
        self.lineEdit_AccessCode.setObjectName("lineEdit_AccessCode")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 641, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_Openfile = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Openfile.setGeometry(QtCore.QRect(540, 20, 91, 21))
        self.btn_Openfile.setObjectName("btn_Openfile")
        self.lineEdit_S19FileLocation = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_S19FileLocation.setGeometry(QtCore.QRect(10, 20, 521, 20))
        self.lineEdit_S19FileLocation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_S19FileLocation.setReadOnly(True)
        self.lineEdit_S19FileLocation.setObjectName("lineEdit_S19FileLocation")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 190, 641, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_Start = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_Start.setGeometry(QtCore.QRect(430, 20, 201, 31))
        self.btn_Start.setObjectName("btn_Start")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(20, 50, 211, 16))
        self.label.setObjectName("label")
        self.progressBarDN = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBarDN.setGeometry(QtCore.QRect(20, 70, 601, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.progressBarDN.setFont(font)
        self.progressBarDN.setProperty("value", 24)
        self.progressBarDN.setObjectName("progressBarDN")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 310, 641, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn_GotoApp = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_GotoApp.setGeometry(QtCore.QRect(150, 20, 341, 31))
        self.btn_GotoApp.setObjectName("btn_GotoApp")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 380, 351, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_Status = QtWidgets.QLabel(self.centralwidget)
        self.label_Status.setGeometry(QtCore.QRect(20, 400, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_Status.setFont(font)
        self.label_Status.setObjectName("label_Status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/DisConnect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisConnect = QtWidgets.QAction(MainWindow)
        self.actionDisConnect.setCheckable(False)
        self.actionDisConnect.setChecked(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Connect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisConnect.setIcon(icon2)
        self.actionDisConnect.setObjectName("actionDisConnect")
        self.menuConnection.addAction(self.actionConnect)
        self.menuConnection.addAction(self.actionDisConnect)
        self.menubar.addAction(self.menuConnection.menuAction())
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionDisConnect)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAN Reprogram - Vector Hardware"))
        self.btn_OpenLog.setText(_translate("MainWindow", "Open CAN UDS Log Data"))
        self.groupBox.setTitle(_translate("MainWindow", "Step 1. Read Application / BootLoader Version"))
        self.btn_ReadAppVer.setText(_translate("MainWindow", "Read Application Version"))
        self.btn_ReadBootVer.setText(_translate("MainWindow", "Read BootLoader Version"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step 2. Go to BootLoader (ECU Reset)"))
        self.btn_GotoBoot.setText(_translate("MainWindow", "Go to BootLoader"))
        self.lineEdit_AccessCode.setText(_translate("MainWindow", "code"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Step 3. Open the Application Software File (.S19)"))
        self.btn_Openfile.setText(_translate("MainWindow", "Open .S19"))
        self.lineEdit_S19FileLocation.setText(_translate("MainWindow", "Open .S19 File"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Step 4. Download && Reprogram the Application Software"))
        self.btn_Start.setText(_translate("MainWindow", "Start DownLoad && Reprogram"))
        self.label.setText(_translate("MainWindow", "DownLoad & Reprogram Progress"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Step 5. Go to Application (ECU Reset)"))
        self.btn_GotoApp.setText(_translate("MainWindow", "Go to Application"))
        self.label_2.setText(_translate("MainWindow", "Status :"))
        self.label_Status.setText(_translate("MainWindow", "Ready to Reprogram"))
        self.menuConnection.setTitle(_translate("MainWindow", "Connection"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisConnect.setText(_translate("MainWindow", "DisConnect"))


import UI.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
