/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : APP
**     Processor   : MC9S12ZVC64MKH
**     Component   : MC9S12ZVC192_64
**     Version     : Component 01.050, Driver 02.08, CPU db: 3.00.000
**     Datasheet   : MC9S12ZVC-Family Reference Manual Preliminary Confidential Rev. 1.7 29-September-2016
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2019-07-22, 13:04, # CodeGen: 7
**     Abstract    :
**         This component "MC9S12ZVC192_64" implements properties, methods,
**         and events of the CPU.
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 02.08
** @brief
**         This component "MC9S12ZVC192_64" implements properties, methods,
**         and events of the CPU.
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

#include "Timer_1ms.h"
#include "CANComm.h"
#include "CANPHY0.h"
#include "LED_ORG.h"
#include "LED_YEL.h"
#include "LED_GR.h"
#include "LED_RED.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x07FFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12ZVC192_64)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12ZVC192_64)
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of prologue code in a function */
#pragma NO_EXIT                        /* Suppress generation of  epilogue code in a function */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 6.5 cycles */
  /* jsr:  2.5 cycles overhead (call this function) */
  /* LD D2,#x:  1 cycles overhead (load parameter into register) */
  /* rts:  3 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 2.5 cycles */
  /* dbne:  4.5 cycles overhead */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
     
     
    /*
     * Delay
     *   - requested                  : 100 us @ 16MHz,
     *   - possible                   : 1600 c, 100000 ns
     *   - without removable overhead : 1595.5 c, 99718.75 ns
     */
    LD D6,#0x0123                      /* (1_5 c: 93.75 ns) number of iterations */
label0:
    DEC D6                             /* (1 c: 62.5 ns) decrement d1 */
    BNE label0                         /* (4 c: 250 ns) repeat 291x */
    /* 100 us delay block end */
    DBNE D2, loop                      /* us100 parameter is passed via D register */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12ZVC192_64)
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12ZVC192_64)
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12ZVC192_64)
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12ZVC192_64)
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12ZVC192_64)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab of the CPU component. !!! ***/



#pragma NO_RETURN                      /* Suppress generation of return from a function */
void _EntryPoint(void)
{

  /*** !!! Here you can place your own code using property "User code before PE initialization" on the build options tab of the CPU compoennt. !!! ***/

  /* ### MC9S12ZVC192_64 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* IVBR: IVB_ADDR=0x7F80,??=0 */
  setReg16(IVBR, 0xFF00U);              
  /* ECLKCTL: NECLK=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(ECLKCTL, 0x80U);              
  /*  System clock initialization */
  /* CPMUPROT: ??=0,??=0,??=1,??=0,??=0,??=1,??=1,PROT=0 */
  setReg8(CPMUPROT, 0x26U);            /* Disable protection of clock configuration registers */ 
  /* CPMUCLKS: PSTP=0 */
  clrReg8Bits(CPMUCLKS, 0x40U);         
  /* CPMUCLKS: PLLSEL=1 */
  setReg8Bits(CPMUCLKS, 0x80U);        /* Enable the PLL to allow write to divider registers */ 
  /* CPMUPOSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(CPMUPOSTDIV, 0x00U);         /* Set the post divider register */ 
  /* Whenever changing PLL reference clock (REFCLK) frequency to a higher value
   it is recommended to write CPMUSYNR = 0x00 in order to stay within specified
   maximum frequency of the MCU */
  /* CPMUSYNR: VCOFRQ1=0,VCOFRQ0=0,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=0,SYNDIV1=0,SYNDIV0=0 */
  setReg8(CPMUSYNR, 0x00U);            /* Set the multiplier register */ 
  /* CPMUREFDIV: REFFRQ1=0,REFFRQ0=1,??=0,??=0,REFDIV3=0,REFDIV2=0,REFDIV1=0,REFDIV0=0 */
  setReg8(CPMUREFDIV, 0x40U);          /* Set the divider register */ 
  /* CPMUOSC2: ??=0,??=0,??=0,??=0,??=0,??=0,OMRE=1,OSCMOD=0 */
  setReg8(CPMUOSC2, 0x02U);            /* Configure external oscillator options */ 
  /* CPMUOSC: OSCE=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(CPMUOSC, 0x80U);             /* Enable the oscillator */ 
  /* CPMUPLL: ??=0,??=0,FM1=0,FM0=0,??=0,??=0,??=0,??=0 */
  setReg8(CPMUPLL, 0x00U);             /* Set the PLL frequency modulation */ 
  /* CPMUSYNR: VCOFRQ1=0,VCOFRQ0=0,SYNDIV5=0,SYNDIV4=0,SYNDIV3=0,SYNDIV2=0,SYNDIV1=1,SYNDIV0=1 */
  setReg8(CPMUSYNR, 0x03U);            /* Set the multiplier register */ 
  while(CPMUIFLG_UPOSC == 0U) {        /* Wait until the oscillator is qualified by the PLL */
  }
  /* CPMUPROT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,PROT=0 */
  setReg8(CPMUPROT, 0x00U);            /* Enable protection of clock configuration registers */ 
  /* CPMUCOP: RSBCK=0,WRTMASK=1 */
  clrSetReg8Bits(CPMUCOP, 0x40U, 0x20U); 
  /* CPMUHTCTL: ??=0,??=0,VSEL=0,??=0,HTE=1,HTDS=0,HTIE=0,HTIF=0 */
  setReg8(CPMUHTCTL, 0x08U);            
  /* CPMUVREGCTL: ??=0,??=0,??=0,??=0,??=0,EXTCON=1,EXTXON=0,INTXON=1 */
  setReg8(CPMUVREGCTL, 0x05U);          
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code using property "User code after PE initialization" on the build options tab of the CPU component. !!! ***/

  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm(jmp _Startup);                 /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12ZVC192_64)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name                 Description */
  setReg8(INT_CFADDR, 0x50U);           
  setReg8(INT_CFDATA4, 0x04U);         /*  0x54  0x00FF0150   4   no   ivVcan0tx            used by PE */ 
  setReg8(INT_CFDATA5, 0x04U);         /*  0x55  0x00FF0154   4   no   ivVcan0rx            used by PE */ 
  setReg8(INT_CFDATA6, 0x04U);         /*  0x56  0x00FF0158   4   no   ivVcan0err           used by PE */ 
  setReg8(INT_CFADDR, 0x70U);           
  setReg8(INT_CFDATA3, 0x04U);         /*  0x73  0x00FF01CC   4   no   ivVtim0ch0           used by PE */ 
  /* Common initialization of the CPU registers */
  /* TIM0TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=1,??=0,??=0,??=0 */
  setReg8(TIM0TSCR1, 0x08U);            
  /* TIM0OCPD: OCPD7=1,OCPD6=1,OCPD5=1,OCPD4=1,OCPD3=1,OCPD2=1,OCPD1=1,OCPD0=1 */
  setReg8(TIM0OCPD, 0xFFU);             
  /* TIM0PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(TIM0PACTL, 0x0CU);        
  /* TIM0OC7M: OC7M0=0 */
  clrReg8Bits(TIM0OC7M, 0x01U);         
  /* TIM0TIOS: IOS7=1,IOS0=1 */
  setReg8Bits(TIM0TIOS, 0x81U);         
  /* TIM0TCTL2: OM0=0,OL0=0 */
  clrReg8Bits(TIM0TCTL2, 0x03U);        
  /* TIM0TTOV: TOV7=0,TOV0=0 */
  clrReg8Bits(TIM0TTOV, 0x81U);         
  /* TIM0TCTL1: OM7=0,OL7=0 */
  clrReg8Bits(TIM0TCTL1, 0xC0U);        
  /* TIM0TSCR2: TOI=0,TCRE=1 */
  clrSetReg8Bits(TIM0TSCR2, 0x80U, 0x08U); 
  /* TIM0TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(TIM0TFLG1, 0xFFU);            
  /* TIM0PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=0 */
  setReg8(TIM0PTPSR, 0x00U);            
  /* TIM0TIE: C0I=0 */
  clrReg8Bits(TIM0TIE, 0x01U);          
  /* MODRR0: M0C0RR&=~3 */
  clrReg8Bits(MODRR0, 0x03U);           
  /* PIEP: PIEP6=0,PIEP5=0,PIEP4=0,PIEP0=0 */
  clrReg8Bits(PIEP, 0x71U);             
  /* PTP: PTP6=0,PTP5=0,PTP4=0,PTP0=0 */
  clrReg8Bits(PTP, 0x71U);              
  /* PERP: PERP6=0,PERP5=0,PERP4=0,PERP0=0 */
  clrReg8Bits(PERP, 0x71U);             
  /* DDRP: DDRP6=1,DDRP5=1,DDRP4=1,DDRP0=1 */
  setReg8Bits(DDRP, 0x71U);             
  /* CPMUINT: LOCKIE=0,OSCIE=0 */
  clrReg8Bits(CPMUINT, 0x12U);          
  /* CPMULVCTL: LVIE=0 */
  clrReg8Bits(CPMULVCTL, 0x02U);        
  /* ECCIE: SBEEIE=0 */
  clrReg8Bits(ECCIE, 0x01U);            
  /* ECCDCMD: ECCDRR=0 */
  clrReg8Bits(ECCDCMD, 0x80U);          
  /* RDRP: RDRP6=0,RDRP5=0,RDRP4=0,RDRP2=0,RDRP0=0 */
  clrReg8Bits(RDRP, 0x75U);             
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ### MC9S12ZVC192_64 "Cpu" init code ... */
  /* ### TimerInt "Timer_1ms" init code ... */
  
  /* TIM0TIE: C0I=1 */
  setReg8Bits(TIM0TIE, 0x01U);          
  
  /* TIM0TC0: BIT=0x3E80 */
  setReg16(TIM0TC0, 0x3E80U);          /* Store given value to the compare register */ 
  /* TIM0TC7: BIT=0x3E80 */
  setReg16(TIM0TC7, 0x3E80U);          /* Store given value to the modulo register */ 
  /* ###  "CANComm" init code ... */
  CANComm_Init();
  /* ### Init_CANPHY "CANPHY0" init code ... */
  /* ### Call "CANPHY0_Init();" init method in a user code, i.e. in the main code */

  /* ### Note:   To enable automatic calling of the "CANPHY0" init code here,
                 the 'Call Init method' property must be set to 'yes'.
   */
  /* ### BitIO "LED_ORG" init code ... */
  /* ### BitIO "LED_YEL" init code ... */
  /* ### BitIO "LED_GR" init code ... */
  /* ### BitIO "LED_RED" init code ... */
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
