/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Vectors.c
**     Project     : APP
**     Processor   : MC9S12ZVC64MKH
**     Version     : Component 01.050, Driver 02.08, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2019-07-22, 13:04, # CodeGen: 7
**     Abstract    :
**         This component "MC9S12ZVC192_64" implements properties, methods,
**         and events of the CPU.
**     Settings    :
**
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Vectors.c                                                  
** @version 02.08
** @brief
**         This component "MC9S12ZVC192_64" implements properties, methods,
**         and events of the CPU.
*/         
/*!
**  @addtogroup Vectors_module Vectors module documentation
**  @{
*/         
#include "Cpu.h"
#include "Timer_1ms.h"
#include "CANComm.h"
#include "CANPHY0.h"
#include "LED_ORG.h"
#include "LED_YEL.h"
#include "LED_GR.h"
#include "LED_RED.h"

/* ISR prototype */
typedef void (*const tIsrFunc)(void);
/* Pack 3 byte pointers as 4 byte Interrupt Vector Table entries */
typedef struct
{
  byte padding;
  tIsrFunc address;
} InterruptTableEntry;
#define _VECTOR(v) {0xFFU, &v}
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
const InterruptTableEntry _InterruptVectorTable[123] @0x00FF0010U = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* ISR name                               No.  Address  Pri Name                 Description */
  _VECTOR(Cpu_Interrupt),               /* 0x04  0x00FF0010   1   ivVReserved123       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x05  0x00FF0014   1   ivVReserved122       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x06  0x00FF0018   1   ivVReserved121       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x07  0x00FF001C   1   ivVReserved120       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x08  0x00FF0020   1   ivVReserved119       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x09  0x00FF0024   1   ivVReserved118       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0A  0x00FF0028   1   ivVReserved117       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0B  0x00FF002C   1   ivVReserved116       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0C  0x00FF0030   1   ivVReserved115       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0D  0x00FF0034   1   ivVReserved114       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0E  0x00FF0038   1   ivVReserved113       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0F  0x00FF003C   1   ivVReserved112       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x10  0x00FF0040   1   ivVReserved111       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x11  0x00FF0044   1   ivVReserved110       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x12  0x00FF0048   1   ivVReserved109       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x13  0x00FF004C   1   ivVReserved108       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x14  0x00FF0050   1   ivVReserved107       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x15  0x00FF0054   1   ivVReserved106       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x16  0x00FF0058   1   ivVReserved105       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x17  0x00FF005C   1   ivVsenttx            unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x18  0x00FF0060   1   ivViic               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x19  0x00FF0064   1   ivVReserved102       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1A  0x00FF0068   1   ivVReserved101       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1B  0x00FF006C   1   ivVReserved100       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1C  0x00FF0070   1   ivVReserved99        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1D  0x00FF0074   1   ivVReserved98        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1E  0x00FF0078   1   ivVReserved97        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1F  0x00FF007C   1   ivVReserved96        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x20  0x00FF0080   1   ivVReserved95        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x21  0x00FF0084   1   ivVReserved94        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x22  0x00FF0088   1   ivVReserved93        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x23  0x00FF008C   1   ivVtim1ovf           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x24  0x00FF0090   1   ivVReserved91        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x25  0x00FF0094   1   ivVReserved90        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x26  0x00FF0098   1   ivVReserved89        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x27  0x00FF009C   1   ivVReserved88        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x28  0x00FF00A0   1   ivVtim1ch3           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x29  0x00FF00A4   1   ivVtim1ch2           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2A  0x00FF00A8   1   ivVtim1ch1           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2B  0x00FF00AC   1   ivVtim1ch0           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2C  0x00FF00B0   1   ivVReserved83        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2D  0x00FF00B4   1   ivVReserved82        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2E  0x00FF00B8   1   ivVReserved81        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2F  0x00FF00BC   1   ivVReserved80        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x30  0x00FF00C0   1   ivVportl             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x31  0x00FF00C4   1   ivVReserved78        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x32  0x00FF00C8   1   ivVReserved77        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x33  0x00FF00CC   1   ivVReserved76        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x34  0x00FF00D0   1   ivVReserved75        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x35  0x00FF00D4   1   ivVReserved74        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x36  0x00FF00D8   1   ivVReserved73        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x37  0x00FF00DC   1   ivVReserved72        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x38  0x00FF00E0   1   ivVReserved71        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x39  0x00FF00E4   1   ivVReserved70        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3A  0x00FF00E8   1   ivVReserved69        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3B  0x00FF00EC   1   ivVReserved68        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3C  0x00FF00F0   1   ivVReserved67        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3D  0x00FF00F4   1   ivVportad            unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3E  0x00FF00F8   1   ivVReserved65        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3F  0x00FF00FC   1   ivVhti               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x40  0x00FF0100   1   ivVapi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x41  0x00FF0104   1   ivVlvi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x42  0x00FF0108   1   ivVevddx             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x43  0x00FF010C   1   ivVportp             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x44  0x00FF0110   1   ivVReserved59        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x45  0x00FF0114   1   ivVReserved58        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x46  0x00FF0118   1   ivVReserved57        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x47  0x00FF011C   1   ivVReserved56        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x48  0x00FF0120   1   ivVReserved55        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x49  0x00FF0124   1   ivVports             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4A  0x00FF0128   1   ivVcanphy0           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4B  0x00FF012C   1   ivVReserved52        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4C  0x00FF0130   1   ivVReserved51        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4D  0x00FF0134   1   ivVReserved50        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4E  0x00FF0138   1   ivVReserved49        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4F  0x00FF013C   1   ivVReserved48        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x50  0x00FF0140   1   ivVbats              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x51  0x00FF0144   1   ivVReserved46        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x52  0x00FF0148   1   ivVReserved45        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x53  0x00FF014C   1   ivVReserved44        unused by PE */
  _VECTOR(CANComm_InterruptTx),         /* 0x54  0x00FF0150   4   ivVcan0tx            used by PE */
  _VECTOR(CANComm_InterruptRx),         /* 0x55  0x00FF0154   4   ivVcan0rx            used by PE */
  _VECTOR(CANComm_InterruptError),      /* 0x56  0x00FF0158   4   ivVcan0err           used by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x57  0x00FF015C   1   ivVcan0wkup          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x58  0x00FF0160   1   ivVflash             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x59  0x00FF0164   1   ivVflasherr          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5A  0x00FF0168   1   ivVReserved37        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5B  0x00FF016C   1   ivVspi1              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5C  0x00FF0170   1   ivVRAM_err           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5D  0x00FF0174   1   ivVacmp1             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5E  0x00FF0178   1   ivVacmp0             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5F  0x00FF017C   1   ivVcpmuplllck        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x60  0x00FF0180   1   ivVcpmuosc           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x61  0x00FF0184   1   ivVadc0conv_compl    unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x62  0x00FF0188   1   ivVadc0conv_seq_abrt unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x63  0x00FF018C   1   ivVadc0err           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x64  0x00FF0190   1   ivVReserved27        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x65  0x00FF0194   1   ivVReserved26        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x66  0x00FF0198   1   ivVsci1              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x67  0x00FF019C   1   ivVsci0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x68  0x00FF01A0   1   ivVspi0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x69  0x00FF01A4   1   ivVtim0paie          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6A  0x00FF01A8   1   ivVtim0paaovf        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6B  0x00FF01AC   1   ivVtim0ovf           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6C  0x00FF01B0   1   ivVtim0ch7           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6D  0x00FF01B4   1   ivVtim0ch6           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6E  0x00FF01B8   1   ivVtim0ch5           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6F  0x00FF01BC   1   ivVtim0ch4           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x70  0x00FF01C0   1   ivVtim0ch3           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x71  0x00FF01C4   1   ivVtim0ch2           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x72  0x00FF01C8   1   ivVtim0ch1           unused by PE */
  _VECTOR(Timer_1ms_Interrupt),         /* 0x73  0x00FF01CC   4   ivVtim0ch0           used by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x74  0x00FF01D0   1   ivVrti               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x75  0x00FF01D4   1   ivVirq               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x76  0x00FF01D8   -   ivVxirq              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x77  0x00FF01DC   -   ivVsi                unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x78  0x00FF01E0   1   ivVReserved7         unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x79  0x00FF01E4   1   ivVReserved6         unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7A  0x00FF01E8   -   ivVme                unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7B  0x00FF01EC   -   ivVsys               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7C  0x00FF01F0   -   ivVswi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7D  0x00FF01F4   -   ivVtrap              unused by PE */
  _VECTOR(Cpu_Interrupt)                /* 0x7E  0x00FF01F8   -   ivVspare             unused by PE */
};

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
const InterruptTableEntry _ResetVectorTable[1] @0x00FFFFFCU = { /* Reset vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* Reset handler name                    Address Name                  Description */
  _VECTOR(_EntryPoint)                  /* 0x00FFFFFC  ivVreset              used by PE */
};
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
